### ISSUE TITLE
cypher-shell shows :The client is unauthorized due to authentication failure.

### ISSUE THREAD

**Issue by YashMishra96** [neo4j/neo4j-javascript-driver#381] opened 2018-06-01 13:16 UTC
I am running neo4j using the shell, I was running some queries and all of a sudden this error popped up, any solution?

**Comment by lutovich** [comment] 2018-06-01 13:32
Hi @YashMishra96,

This error does not seem to be related to the JavaScript driver. Cypher shell is built in Java and uses the Java driver underneath. Relevant repo is here: https://github.com/neo4j/cypher-shell.

Such errors happen only when provided credentials are incorrect. Can you provide steps to reproduce?

**Comment by YashMishra96** [comment] 2018-06-01 13:44
I have started the server through the command neo4j<Home>/bin/neo4j console.
and then opened another terminal and opened cypher shell using neo4j<Home./bin/cypher-shell -u neo4j -p neo4j.
I was able to start the shell this way.
I was then prompted to change my password and I did that using the command CALL dbms.security.changePassword('evdy!!'). The shell was running well after this but suddenly when I ran a query this error prompted 'The client is unauthorized due to authentication failure'.
Please suggest a solution.

**Comment by lutovich** [comment] 2018-06-01 15:17
When password is changed in cypher-shell it is still possible to continue using the current connection. Database does not logout user after a password change. However, it will not be possible to establish new connections because the initially provided credentials are no longer valid. Thus it is required to restart the cypher-shell after a password change.

I can reproduce the described behavior by changing the password in cypher-shell and then killing the TCP connection using the following two commands:

```
netstat -lanW | grep 7687.*ESTABLISHE
sudo tcpkill -i lo0 host 127.0.0.1 port 58300
```

Shell session experiences a "Connection reset by peer" error and then all subsequent queries fail with "The client is unauthorized due to authentication failure". Shell works after `:exit` and restart with new credentials. I can recommend using `bin/neo4j-admin set-initial-password` to change the password right after neo4j installation or neo4j-browser with its change-password prompt or cypher-shell with manual re-login.

I'll close this issue now. Please feel free to update it if the problem persists.

**Closed as completed by lutovich** 2018-06-01 15:17 UTC
