### ISSUE TITLE
Socket stays open on Neo4J Server

### ISSUE THREAD

**Issue by ranlandau** [neo4j/neo4j-javascript-driver#275] opened 2017-07-19 13:54 UTC
Hi,

we are using neo4j-driver, we stumbled upon a strange behavior.
as far as we use it, the server starts slowing down and become heavy and heavy

we did use a queue, which runs maximum of 4 sessions at once against our neo4j server, but we still get to a point where server stops replying.

when investigating it deeply, we saw the amount of open sockets on our neo4j machine is growing and growing and only closes with a connection reset by peer timeout.

running the following command, gave this result: 
netstat -an | grep ESTABLISHED | wc -l
7641

which counts the "established" sockets in the system.,
e.g.:
tcp6       0      0 ip-10-1-32-39.ec2.:7687 ip-10-1-64-124.ec:53664 ESTABLISHED -
tcp6       0      0 ip-10-1-32-39.ec2.:7687 ip-10-0-0-148.ec2:59127 ESTABLISHED -
tcp6       0      0 ip-10-1-32-39.ec2.:7687 ip-10-0-0-148.ec2:52404 ESTABLISHED -
tcp6       0      0 ip-10-1-32-39.ec2.:7687 ip-10-0-0-148.ec2:59165 ESTABLISHED -
tcp6       0      0 ip-10-1-32-39.ec2.:7687 ip-10-1-64-124.ec:53496 ESTABLISHED -
tcp6       0      0 ip-10-1-32-39.ec2.:7687 ip-10-0-0-148.ec2:59622 ESTABLISHED -
tcp6       0      0 ip-10-1-32-39.ec2.:7687 ip-10-0-0-148.ec2:56702 ESTABLISHED -
tcp6       0      0 ip-10-1-32-39.ec2.:7687 ip-10-0-0-148.ec2:54837 ESTABLISHED -
tcp6       0      0 ip-10-1-32-39.ec2.:7687 ip-10-0-0-148.ec2:58306 ESTABLISHED -

my code that actually runs

` 

Neo4jSession.prototype.addDefaultSession  = function(){
  var driver =  this.getDefaultDriver();
  var session = driver.session();
  return session;
}

Neo4jSession.prototype.run  = function(cypherQuery){
  var neo4jSessionObj = this;

  var job = function(){
    return new Promise(function(resolve, reject){
    var session = neo4jSessionObj.addDefaultSession();
    //this.addActiveSession(session);
    session.run(cypherQuery)
    .then(function(res){
      session.close();
      resolve(res);
    })
    .catch(function(err){
      session.close();
      reject(err);
    })
  })
  }
  

//add a single job

return queue.push(job).then(function(res){return res;}.catch(function (err){ return err; }));

}
`

**Comment by lutovich** [comment] 2017-07-19 15:29
Hi @ranlandau,

Which version of the database and neo4j-driver are you using?
Do you have database logs (`debug.log` and `neo4j.log`) for the period when this problem has happened?

Provided code looks correct, it should always result in connections being returned to the pool (and closed, if needed). Is this the only way you executed queries?

**Comment by ranlandau** [comment] 2017-07-20 08:57
hi @lutovich 

i'm using neo4j-driver (1.5) and neo4j enterprise 3.2.2
I do have logs and i see the following error in the debug.log (neo4j.log isn't generated for some reason)

And yes, this is my only execution.
Some sockets are closed, but many stays open and i actually go to 11K of open sockets now, then neo4j server doesn't respond anymore.

but must i say, all queries return correctly with no errors.

2017-07-20 08:22:47.426+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [30]:  Log pruning complete.
2017-07-20 08:26:18.491+0000 ERROR [o.n.b.v.t.BoltProtocolV1] Failed to write response to driver Cannot write to buffer when closed
java.io.IOException: Cannot write to buffer when closed
        at org.neo4j.bolt.v1.transport.ChunkedOutput.ensure(ChunkedOutput.java:163)
        at org.neo4j.bolt.v1.transport.ChunkedOutput.writeByte(ChunkedOutput.java:86)
        at org.neo4j.bolt.v1.packstream.PackStream$Packer.packMapHeader(PackStream.java:402)
        at org.neo4j.bolt.v1.messaging.Neo4jPack$Packer.packRawMap(Neo4jPack.java:238)
        at org.neo4j.bolt.v1.messaging.BoltResponseMessageWriter.onSuccess(BoltResponseMessageWriter.java:77)
        at org.neo4j.bolt.v1.messaging.MessageProcessingHandler.onFinish(MessageProcessingHandler.java:111)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.after(BoltStateMachine.java:103)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.reset(BoltStateMachine.java:176)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onReset$2(BoltMessageRouter.java:74)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:130)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:91)
        at java.lang.Thread.run(Thread.java:748)
2017-07-20 08:28:31.662+0000 ERROR [o.n.b.v.t.BoltProtocolV1] Failed to write response to driver Cannot write to buffer when closed
java.io.IOException: Cannot write to buffer when closed
        at org.neo4j.bolt.v1.transport.ChunkedOutput.ensure(ChunkedOutput.java:163)
        at org.neo4j.bolt.v1.transport.ChunkedOutput.writeShort(ChunkedOutput.java:94)
        at org.neo4j.bolt.v1.packstream.PackStream$Packer.packStructHeader(PackStream.java:427)
        at org.neo4j.bolt.v1.messaging.BoltResponseMessageWriter.onSuccess(BoltResponseMessageWriter.java:76)
        at org.neo4j.bolt.v1.messaging.MessageProcessingHandler.onFinish(MessageProcessingHandler.java:111)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.after(BoltStateMachine.java:103)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.reset(BoltStateMachine.java:176)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onReset$2(BoltMessageRouter.java:74)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:130)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:91)
        at java.lang.Thread.run(Thread.java:748)
2017-07-20 08:31:47.597+0000 ERROR [o.n.b.v.t.BoltProtocolV1] Failed to write response to driver Cannot write to buffer when closed
java.io.IOException: Cannot write to buffer when closed
        at org.neo4j.bolt.v1.transport.ChunkedOutput.ensure(ChunkedOutput.java:163)
        at org.neo4j.bolt.v1.transport.ChunkedOutput.writeShort(ChunkedOutput.java:94)
        at org.neo4j.bolt.v1.packstream.PackStream$Packer.packStructHeader(PackStream.java:427)
        at org.neo4j.bolt.v1.messaging.BoltResponseMessageWriter.onSuccess(BoltResponseMessageWriter.java:76)
        at org.neo4j.bolt.v1.messaging.MessageProcessingHandler.onFinish(MessageProcessingHandler.java:111)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.after(BoltStateMachine.java:103)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.reset(BoltStateMachine.java:176)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onReset$2(BoltMessageRouter.java:74)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:130)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:91)
        at java.lang.Thread.run(Thread.java:748)
2017-07-20 08:37:47.605+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [218470]:  Starting check pointing...

**Comment by lutovich** [comment] 2017-07-20 09:04
Hi @ranlandau,

These errors are not pretty but not critical. They usually mean connection was closed by the client and server was not able to write back a response. They should become prettier and more accurate with [this PR](https://github.com/neo4j/neo4j/pull/9658). I can't really tell if they are related to the issue you are seeing. Do you have any `OutOfMemoryError`s in the `debug.log`?

Could you please also share code of `getDefaultDriver` function?

**Comment by ranlandau** [comment] 2017-07-20 09:34
Hi again @lutovich 

Yes i understand that, but i assume that overloads my server's sockets?

Here's the code:

var Neo4jSession = function()
{
    this.defaultDriver = this.setDefaultDriver();
}

Neo4jSession.prototype.setDefaultDriver  = function(){
  var url = Neo4jConfigurator.instance().getDBURlIndexer();
  var driver = neo4j.driver("bolt://" + url,  neo4j.auth.basic(userName, password),{maxIdleConnectionPoolSize: 1000, idleTimeBeforeConnectionTest:10, connectionTimeoutMillis:3600, encrypted:false, connectionPoolSize : 5, maxTransactionRetryTime: 30000});
  return driver;
}

Neo4jSession.prototype.getDefaultDriver  = function(){
  return this.defaultDriver;
}

Neo4jSession.prototype.addDefaultSession  = function(){
  var driver =  this.getDefaultDriver();
  var session = driver.session();
  return session;
}

**Comment by lutovich** [comment] 2017-07-20 10:08
@ranlandau those errors only tell us that client closes some connections for some reason. I'm not sure this could overload the system. However excessive amount of connections can definitely cause an overload.

How do you instantiate and use `Neo4jSession` objects? It looks like every `new Neo4jSession()` call will create a new driver. Each driver holds a connection pool where it keeps idle connections. If driver is not explicitly closed, all those open connections will remain open.

Could you please share code that creates and used `Neo4jSession`s? It might be that they are created often (for every interaction with the database?) and never closed. Which will result in multiple open driver instances that hold open connections.

**Comment by jcontesse** [comment] 2017-11-23 21:09
I am having the exact same problem (https://stackoverflow.com/questions/47398872/neo4j-with-small-graph-uses-a-lot-of-memory-on-ubuntu-16-04). I found out it is because of open connections. I believe I am closing the sessions and driver properly. Whe I close my app, all connections are closed.

**Comment by danilovergara** [comment] 2017-11-23 21:43
I'm working alongside @jcontesse. We are making a daemon that initialize a pseudo-singleton for a Neo4J session at start, and when it gets a SIGINT, closes the connection. The objective is to create a unique Neo4j connection. We use a Helper to encapsulate this process.

This is the code for the Helper:

```javascript
const neo4j = require('neo4j-driver').v1;
const config = require('../config/config');

let _driver = neo4j.driver(
	config.neo4j.uri, 
	neo4j.auth.basic(config.neo4j.user, config.neo4j.pass)
);

let _session = _driver.session();

class Helper{
	static getNeo4jDriver() {
		return _session;
	}

	static async closeNeo4jDriver() {
		await _driver.close();
	}
}

module.exports = Helper;
```

We use it as follows:

```javascript
async _verifyNeo4j(){
    let session = Helper.getNeo4jDriver();
    
    try{

        let query = `
            MATCH (n)
            RETURN n
            LIMIT 1
        `;

        let result = await session.run(query);
        return true;
    }catch(err){
        throw new Error('Neo4j is down');
    }
}
```

This is the register of the SIGINT signal:

```javascript
process.on('SIGINT', () => {
    Helper.closeNeo4jDriver();
    process.exit(0);
});
```

We are using Node 8.1.4, and the latest version of neo4j-driver (1.5.0)

**Comment by lutovich** [comment] 2017-11-23 23:32
Hi @jcontesse, @danilovergara.

I tried to reproduce described issue with the following script:

```javascript
const async = require('async');
const neo4j = require('neo4j-driver').v1;
const exec = require('child_process').exec;

const driver = neo4j.driver('bolt://localhost', neo4j.auth.basic('neo4j', 'test'));

const session = driver.session();

const pid = process.pid;
console.log('PID: ' + pid);

class Helper {
  static getNeo4jDriver() {
    return session;
  }

  static closeNeo4jDriver() {
    driver.close();
  }
}

async function runQuery(read, callback) {
  const session = Helper.getNeo4jDriver();

  // const session = driver.session();
  const query = read ? 'MATCH (n) RETURN n LIMIT 1' : 'CREATE (n:Node {id: 42}) RETURN n';

  try {
    const result = await session.run(query);
    if (result.records.length !== 1) {
      callback(new Error('Illegal number of records: ' + result.records));
    } else {
      callback();
    }
  } catch (e) {
    callback(e);
  } finally {
    // session.close();
  }
}

async function runTest() {
  await runQuery(false, () => {
  });

  const queriesToRun = 1000000;
  const parallelLimit = 20;

  const queryFunctions = Array.from(Array(queriesToRun).keys())
    .map(index => callback => runQuery(index % 2 === 0, callback));

  async.parallelLimit(
    queryFunctions,
    parallelLimit,
    error => {
      if (error) {
        console.log('Queries failed: ', error);
      } else {
        console.log('Queries succeeded');
      }

      // check *private* property of the driver
      const connectionCount = Object.keys(driver._openSessions).length;
      console.log('At the end of the test driver has ' + connectionCount + ' connections');

      console.log('Executing lsof -p ' + pid);
      exec('lsof -p ' + pid, (error, stdout, stderr) => {
        if (error) {
          console.log('Unable to execute lsof');
        } else {
          console.log('stdout:\n---\n', stdout, '\n---');
          console.log('stderr:\n---\n', stderr, '\n---');
        }

        console.log('Closing driver');
        Helper.closeNeo4jDriver();
        console.log('Driver closed');
      });
    }
  );
}

runTest();

```

but everything worked as expected.

Things to note about the script:
 * contains both use of `Helper` class and recommended open-session-run-query-close-session patterns; uses one at a time, comment one & uncomment the other
 * uses `async` library to execute multiple queries in parallel
 * executes mix of read and write queries
 * fails if any of the queries fail
 * uses **private** property of the driver to print number of connections at the end of the test
 * prints `lsof` for self PID at the end of the test

Used node 8.1.4, driver 1.5.0 and neo4j 3.3.0.

Could you please review the script and suggest how can I reproduce the problem? Or maybe provide a whole script to reproduce it?

I can suggest two things now:
 1) open and close session for every query, like script does or like in the readme. current pattern with single session feels strange, session is like a "unit of work" container. it can't cause connection leak, just feels strange
 2) since 1.5.0 driver it's possible to limit amount of connections in the connection pool. see this [docs section](https://neo4j.com/docs/developer-manual/current/drivers/client-applications/#driver-config-connection-pool-management). consider tuning `maxConnectionPoolSize` and `connectionAcquisitionTimeout`

**Comment by danilovergara** [comment] 2017-11-28 21:23
Hi @lutovich.

We revised our code and found an unclosed connection in one of the queries. We fixed that and it worked. Additionally, we are taking your suggestions for making the connection (timeout and open/close sessions for every query). Maybe @ranlandau have a similar problem.

Thank you for your help.

**Comment by lutovich** [comment] 2017-11-28 21:45
Hi @danilovergara,

Thanks for the update. Great that you found the problem!
I'll close this issue now - it did not have updates about the original issue for a long time.
@ranlandau please write an update if you still experience similar issues.

**Closed as completed by lutovich** 2017-11-28 21:45 UTC

**Comment by ranlandau** [comment] 2017-11-29 11:57
@lutovich we did find some wrong internal behavior with the sessions and fixed it.
Thanks

**Comment by lutovich** [comment] 2017-11-29 12:17
@ranlandau thanks for the update. Glad issue is now resolved!
