### ISSUE TITLE
Internal TypeError on beginTransaction()

### ISSUE THREAD

**Issue by HEmile** [neo4j/neo4j-javascript-driver#661] opened 2021-01-05 18:37 UTC
I'm getting a TypeError when beginning a Transaction on a Session.

```javascript
let driver = neo4j.driver("neo4j://localhost",
            neo4j.auth.basic('neo4j', this.settings.password), {
                maxTransactionRetryTime: 30000
            });
        this.connection = driver.session();
        this.connection.beginTransaction();
```

This gives the error referring to this line: `var mode = _driver["default"]._validateSessionMode(accessMode);`

```
session.js:215 Uncaught (in promise) TypeError: Cannot read property '_validateSessionMode' of undefined
    at Session._beginTransaction (eval at <anonymous> (app.js:1), <anonymous>:15475:37)
    at Session.beginTransaction (eval at <anonymous> (app.js:1), <anonymous>:15462:19)
    at Neo4jStream.eval (eval at <anonymous> (app.js:1), <anonymous>:89296:41)
    at step (eval at <anonymous> (app.js:1), <anonymous>:85:23)
    at Object.eval [as next] (eval at <anonymous> (app.js:1), <anonymous>:66:53)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:59:71)
    at new Promise (<anonymous>)
    at __awaiter (eval at <anonymous> (app.js:1), <anonymous>:55:12)
    at Neo4jStream.start (eval at <anonymous> (app.js:1), <anonymous>:89281:16)
    at Neo4jViewPlugin.eval (eval at <anonymous> (app.js:1), <anonymous>:89518:38)
```

Normally running a query seems to work fine.

- Neo4j version: Community
- Neo4j Mode: Single instance
- Driver version: Javascript Driver 4.2.1
- Operating system: macOS Catalina

I'm also using Typescript/rollup.

**Comment by bigmontz** [comment] 2021-01-07 10:30
Hi @HEmile, I tried to reproduce the error in a small typescript project, but it was not reproduced. 

Could you try without the `rollup`? I will have to some research to understand if `rollup` could interfere with the driver code somehow.

**Comment by HEmile** [comment] 2021-01-07 10:50
Thanks for the response @bigmontz . I tried the following without `rollup`, which just outputs "commit". Exactly the same code crashes with the TypeError when compiling my code with `rollup`.

```javascript
let driver = neo4j.driver("neo4j://localhost",
    neo4j.auth.basic('neo4j', "..."), {
        maxTransactionRetryTime: 30000
    });
let connection = driver.session();
let t = connection.beginTransaction();

t.commit().then(v => {
    console.log("commit");
    connection.close();
});

```

**Comment by bigmontz** [comment] 2021-01-07 13:24
Could you share your `rollup` configuration to understand what could be the issue?

**Comment by HEmile** [comment] 2021-01-07 13:46
```javascript
import typescript from '@rollup/plugin-typescript';
import {nodeResolve} from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';

export default {
  input: 'main.ts',
  output: {
    dir: '.',
    sourcemap: 'inline',
    format: 'cjs',
    exports: 'default'
  },
  external: ['obsidian'],
  plugins: [
    typescript(),
    nodeResolve({browser: true}),
    commonjs(),
  ]
};
```

**Comment by bigmontz** [comment] 2021-01-07 18:07
Hi @HEmile,

I've done some tests with your `rollup` configuration and I've managed to reproduce the error. The error actual error is the `_driver` variable having `{ "default": undefined }" as value. During the build, I've noticed these warnings:

```
!) Circular dependencies
node_modules/neo4j-driver/lib/internal/stream-observers.js -> node_modules/neo4j-driver/lib/internal/connection.js -> node_modules/neo4j-driver/lib/internal/stream-observers.js
node_modules/neo4j-driver/lib/internal/stream-observers.js -> node_modules/neo4j-driver/lib/internal/connection.js -> node_modules/neo4j-driver/lib/internal/bolt-protocol-v1.js -> node_modules/neo4j-driver/lib/internal/bolt-protocol-util.js -> node_modules/neo4j-driver/lib/internal/stream-observers.js
node_modules/neo4j-driver/lib/internal/stream-observers.js -> node_modules/neo4j-driver/lib/internal/connection.js -> node_modules/neo4j-driver/lib/internal/bolt-protocol-v1.js -> node_modules/neo4j-driver/lib/internal/bolt-protocol-util.js -> /Users/antoniobarcelos/bigmontz/movies-ts/node_modules/neo4j-driver/lib/internal/stream-observers.js?commonjs-proxy -> node_modules/neo4j-driver/lib/internal/stream-observers.js
...and 10 more
```
When I've removed the `@rollup/plugin-node-resolve` from the list of plugins, the warning just disappeared and the code executed properly. So the combination of these circular dependencies and the `nodeResolve` are "creating" this error scenario.

I've searched for this kind of error using this plugin, I've found a non solved question the [StackOverflow](https://stackoverflow.com/questions/60973810/how-to-remove-circular-dependencies-in-d3-selection-using-rollupjs) and [an issue on the rollup repository](https://github.com/rollup/rollup/issues/1507), the issue is not resolved either. There is a [suggested solution](https://github.com/rollup/rollup/issues/1507#issuecomment-491555244) using `rollup-plugin-jspm` but I could not make it works properly.

I will continue searching for a solution for this, please update me if you get any news about the issue. 

PS: We are already working for remove theses circular dependencies.

**Comment by HEmile** [comment] 2021-01-07 18:55
Thanks @bigmontz . That's a nasty bug! I tried my config without node-resolve, but that just broke the rest of the configuration...
I'll do a quick scan for other fixes, but I'm afraid that won't be easy. 

> PS: We are already working for remove theses circular dependencies.

That's nice to hear! That would solve this issue, right? What kind of ETA is there for this?

**Comment by bigmontz** [comment] 2021-01-13 12:40
Hi @HEmile, sorry for the delayed reply. It could take some months because it's a part of a bigger change. 

I not entirely sure if it will solve the issue, it could have more issues*  being hidden by the cyclic dependencies. I will keep this rollup scenario under the radar.  

*issues working with the `@rollup` + `@rollup/plugin-node-resolve` + `neo4j-driver`

**Comment by HEmile** [comment] 2021-01-13 12:49
Fair enough. I'll keep following it. In the meanwhile, I'll just create sessions manually without transactions

**Comment by bigmontz** [comment] 2021-01-18 11:07
@HEmile, 

I have a good news. It was not complicated to remove the circular dependencies was missing in the code. Then I've tested your rollup scenario here and it worked as expected. Could you check if the code in `4.3` branch solves the issue for your use case? 

PS: I don't recommend to use this code in production, because it still in dev.

**Comment by HEmile** [comment] 2021-01-19 14:22
Hi @bigmontz ,

Thank you for looking into this issue so soon. I've tried to see if I could get it to work by doing the following:
I replaced in my package.json the neo4j-driver dependency with `"neo4j-driver": "https://github.com/neo4j/neo4j-javascript-driver/tarball/4.3",`, then ran `npm i`. It installs properly into node_modules, with the right version. But for some reason, when I run rollup now, rollup is treating it as an external dependency:

```
(!) Circular dependencies
node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/stream-observers.js -> node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/connection.js -> node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/stream-observers.js
node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/stream-observers.js -> node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/connection.js -> node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/bolt-protocol-v1.js -> node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/bolt-protocol-util.js -> node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/stream-observers.js
node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/stream-observers.js -> node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/connection.js -> node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/bolt-protocol-v1.js -> node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/bolt-protocol-util.js -> /Users/emile/Projects/markdown-typed-links-converter/neo4j-graph-view/node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/stream-observers.js?commonjs-proxy -> node_modules/neovis.js/node_modules/neo4j-driver/lib/internal/stream-observers.js
...and 23 more
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
neo4j-driver (imported by main.ts, stream.ts)
path (imported by stream.ts)
buffer (imported by buffer?commonjs-external)
tls (imported by tls?commonjs-external)
string_decoder (imported by string_decoder?commonjs-external)
dns (imported by dns?commonjs-external)
net (imported by net?commonjs-external)
fs (imported by fs?commonjs-external)
```
EDIT: This also happens without `cypher-query-builder` and `neovis.js`

**Comment by bigmontz** [comment] 2021-01-20 14:46
Hi @HEmile, 

could you try to do a bit different? 

Try to clone the driver locally then run:

`npm i && npm run build`

Then, in your repository folder run:

`npm link $PATH_TO_DRIVER_CLONE`

**Comment by HEmile** [comment] 2021-01-20 16:13
Hi @bigmontz ,

Just tried that. It now gives

```
[!] Error: 'default' is not exported by ../../neo4j-javascript-driver/lib/index.js, imported by stream.ts
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
stream.ts (6:7)
4: import { Query, node, relation } from 'cypher-query-builder';
5: import { SyncQueue } from './sync';
6: import neo4j from 'neo4j-driver';
          ^
7: import { basename } from 'path';
8: export const CAT_DANGLING = 'SMD_dangling';
Error: 'default' is not exported by ../../neo4j-javascript-driver/lib/index.js, imported by stream.ts
    at error (/Users/emile/Projects/markdown-typed-links-converter/neo4j-graph-view/node_modules/rollup/dist/shared/rollup.js:4533:30)
    at Module.error (/Users/emile/Projects/markdown-typed-links-converter/neo4j-graph-view/node_modules/rollup/dist/shared/rollup.js:9917:16)
    at Module.traceVariable (/Users/emile/Projects/markdown-typed-links-converter/neo4j-graph-view/node_modules/rollup/dist/shared/rollup.js:10310:29)
    at ModuleScope.findVariable (/Users/emile/Projects/markdown-typed-links-converter/neo4j-graph-view/node_modules/rollup/dist/shared/rollup.js:8789:39)
    at ChildScope.findVariable (/Users/emile/Projects/markdown-typed-links-converter/neo4j-graph-view/node_modules/rollup/dist/shared/rollup.js:2622:38)
    at ClassBodyScope.findVariable (/Users/emile/Projects/markdown-typed-links-converter/neo4j-graph-view/node_modules/rollup/dist/shared/rollup.js:2622:38)
    at FunctionScope.findVariable (/Users/emile/Projects/markdown-typed-links-converter/neo4j-graph-view/node_modules/rollup/dist/shared/rollup.js:2622:38)
    at ChildScope.findVariable (/Users/emile/Projects/markdown-typed-links-converter/neo4j-graph-view/node_modules/rollup/dist/shared/rollup.js:2622:38)
    at FunctionScope.findVariable (/Users/emile/Projects/markdown-typed-links-converter/neo4j-graph-view/node_modules/rollup/dist/shared/rollup.js:2622:38)
    at ChildScope.findVariable (/Users/emile/Projects/markdown-typed-links-converter/neo4j-graph-view/node_modules/rollup/dist/shared/rollup.js:2622:38)
```
(I'll readily admit I'm not an expert on Node.js dependencies...)

**Comment by bigmontz** [comment] 2021-01-29 10:22
Hi @HEmile,

maybe it could be something with the TS configuration. My `tsconfig.json`

```
{
    "compilerOptions": {
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "strictNullChecks": true,
        "moduleResolution": "node",
        "types": []
    }
}
```

**Comment by bigmontz** [comment] 2021-04-15 11:27
Hi @HEmile, the **alpha** version of the javascript driver was released today (4.3.0-alpha01). It's not production ready, but you could use to validate if the changed made solved your issue. 

Kind regards

**Comment by HEmile** [comment] 2021-04-15 11:43
Thanks for mentioning! I was just about to return to this project so I'll let you know

**Comment by bigmontz** [comment] 2021-05-28 11:04
@HEmile, 4.3 is officially out. I will close this issue. If you have any issue, let me know.

**Closed as completed by bigmontz** 2021-05-28 11:04 UTC
Labels: enhancement
