### ISSUE TITLE
Attempting write in a read txn should fail

### ISSUE THREAD

**Issue by jasperblues** [neo4j/neo4j-javascript-driver#295] opened 2017-10-02 23:37 UTC
On a single instance setup, attempting write in a read transaction will actually work. However, when using BOLT+Routing, could fail if the txn is not routed to master. 

- Ensure failure when performing writes in a read-txn, to prevent trouble when migrating to a cluster.  
- Perhaps include a flag to disable this feature and exhibit the old behavior. (To allow upgrades/bug-fixes before fixing incorrect txn usage).

**Comment by lutovich** [comment] 2017-10-03 08:07
Hi @jasperblues,

Writing in a read session/transaction does fail for me. Following code:

```javascript
const neo4j = require('neo4j-driver').v1;
const driver = neo4j.driver('bolt+routing://localhost:20003', neo4j.auth.basic('neo4j', 'test'));
const session = driver.session(neo4j.session.READ);
const tx = session.beginTransaction();
tx.run('CREATE ()').then(result => {
    driver.close();
    console.log('Result: ', result);
}).catch(error => {
    driver.close();
    console.log('Error: ', error);
});
```

results in:

```
Error:  { Neo4jError: No longer possible to write to server at localhost:20015
    at Neo4jError.Error (native)
    at new Neo4jError (/private/tmp/apa/node_modules/neo4j-driver/lib/v1/error.js:76:132)
    at newError (/private/tmp/apa/node_modules/neo4j-driver/lib/v1/error.js:66:10)
    at _TransactionStreamObserver._errorTransformer (/private/tmp/apa/node_modules/neo4j-driver/lib/v1/routing-driver.js:97:38)
    at _TransactionStreamObserver.onError (/private/tmp/apa/node_modules/neo4j-driver/lib/v1/internal/stream-observer.js:133:35)
    at /private/tmp/apa/node_modules/neo4j-driver/lib/v1/transaction.js:227:168
    at process._tickCallback (internal/process/next_tick.js:109:7) code: 'SessionExpired', name: 'Neo4jError' }
```

Driver sends query to the read server and it responds with an error.

Could you please explain a bit more about your setup and maybe give some simple code to reproduce the problem?

**Comment by jasperblues** [comment] 2017-10-03 08:09
@lutovich Last time (months ago) I tried writing in a read txn, it worked. I opened another issue related to bolt protocol. (I forget the details now). Will test again, get back to you shortly.

**Comment by lutovich** [comment] 2017-10-03 08:13
@jasperblues okey, will wait for your reply. Actually, I made a typo initially and was able to write in what I thought was a read session: used wrong constant `neo4j.READ` instead of `neo4j.session.READ`.

**Comment by jasperblues** [comment] 2017-10-03 08:20
Failing test (indeed, it still fails) is the commented out one here: 
https://github.com/appsquickly/node-neo4j-bolt-adapter/blob/master/test/node-neo4j-bolt-adapter-spec.js

```javascript
    it('should not be able to perform writes in a read txn', (done) => {
        boltAdapter.cypherQueryAsync('CREATE (p:Person {name: "Jasper Blues", born: 1976}) RETURN p')
            .then(result => {
                done(new Error("Write in a read txn should have rejected"));
            })
            .catch(err => {
                //Expected
                done()
            });

    });
```

Where the cypherQueryAynsc method is an adapter to make this driver behave as a drop-in-replacement for the popular http community driver from FiftyThree: (https://github.com/thingdom/node-neo4j)

```javascript 
    cypherQueryAsync(query, params) {

        const self = this;
        return new Promise(function (resolve, reject) {

            const session = self.driver.session();
            const readPromise = session.readTransaction(transaction => transaction.run(query, params));

            readPromise.then(result => {
                session.close();
                resolve(self.mapper.mapToNative(result.records))
            }).catch(err => {
                session.close();
                reject(err)
            })
        })
    }
```

**Comment by lutovich** [comment] 2017-10-03 08:54
Ah, sorry I did not read the question properly. Access mode string and `#readTransaction()` / `#writeTransaction()` only tell driver where to route queries. Currently we do not transfer access mode to server and so it does not constrain query execution.

Making database adhere to the client access mode is on our road map. Let's keep this issue open for now.

**Comment by jasperblues** [comment] 2017-10-03 09:08
Sounds good. I recall now, that was the issue opened earlier. 

Meanwhile, I was actually wondering if it would be feasible to implement on the client side?

**Comment by lutovich** [comment] 2017-10-03 09:10
I think, fixing this on the client side will require driver to parse and understand Cypher queries. This is something we'd like to avoid for now.

**Comment by jasperblues** [comment] 2017-10-03 09:12
Yeah, I guess to do it nicely, building a syntax tree would be necessary.

**Comment by zhenlineo** [comment] 2018-05-11 09:46
Hi @jasperblues,

If I understand, there is no issue in this issue? Let's first describe the things happening here:
Observation 1: if we run a write query in a tx with a READ access mode in a cluster environment, the tx fails. 
Observation 2: if we do the same in a single instance setup, the tx succeed.

The reason that lead to the above observations is that the access mode is merely a information used by the driver for routing. It is not a way to create "read/write transactions".

For a single instance, running a write query in a tx with a READ access mode means that this write query should be routed to a read server and be executed there. In a single instance setup, it does not fail as the reader server is also the write server. If you think this access mode in this way, then we shall not throw any exceptions.

Lesson learned for us: we will improve our docs and also consider improving the API in the future to help community users to also use it smoothly.

And I am closing this issue as I did not see a direct actionable item. Please be free to reopen this if you think there is something that we shall act on.

Cheers,
Zhen

**Closed as completed by zhenlineo** 2018-05-11 09:46 UTC

**Comment by technige** [comment] 2018-10-17 07:52
![](https://github.trello.services/images/mini-trello-icon.png) [Pass access mode to server](https://trello.com/c/IjO5CAvY/368-pass-access-mode-to-server)

**Comment by senica** [comment] 2019-05-05 15:35
Just a note for others. We were writing inside a read transaction on accident. On local testing (server running in SINGLE mode) it worked just fine. On deployment in a cluster, it would fail. Took us a minute to figure out what was going on.
