### ISSUE TITLE
Neo4jError: Failed to establish connection in 5000ms

### ISSUE THREAD

**Issue by 2joocy** [neo4j/neo4j-javascript-driver#467] opened 2019-05-23 22:53 UTC
Running more than one function will cause the connection to timeout. Here's the project incase you want full context
https://github.com/2joocy/ImportData

The issue is in `index.ts`

If I were to run these 2 functions at the same time, I would get a timeout, saying it couldn't establish connection in 5000ms

```
createAuthorAndBook(authors[0], title);
createCityRelationToBook(title, mentionedCities[1])
```` 

The sourcecode for both of these functions are:

```
export function createAuthorAndBook(name: string, title: string): Promise<boolean>{
    const resultPromise = session.run(
        `Create(a: Author {name: $name
        })
        Create(b: Book {
            title: $title
        })
        CREATE (a)-[r:Wrote]->(b);`,
        { title: title, name: name }
    );
    return new Promise((resolve, reject) => {
        const result = resultPromise.then((result: any) => {
            resolve(true);
        }).catch((err: any) => reject(err));
    })
}

export function createCityRelationToBook(title:string, city: string): Promise<boolean>{
    const resultPromise = session.run(
        `MATCH(b: Book { title: $title })
        MATCH(a: Location { name: $name })
        CREATE (a)-[r:Mentions]->(b);`,
        { title: title, name: city }
    );
    return new Promise((resolve, reject) => {
        const result = resultPromise.then((result: any) => {
            resolve(true);
        }).catch((err: any) => reject(err));
    })
}
```

connecting is done fairly simple, at the top of my neo4j class as such
```
const driver = neo4j.driver(NEO4J_URL, neo4j.auth.basic(NEO4J_USER, NEO4J_PASS));
const session = driver.session();
```
The full stacktrace is:

```
(node:9492) UnhandledPromiseRejectionWarning: Neo4jError: Failed to establish connection in 5000ms
:
    at captureStacktrace (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\result.js:200:15)
    at new Result (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\result.js:73:19)
    at Session._run (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\session.js:173:14)
    at Session.run (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\session.js:154:19)
    at Object.createCityRelationToBook (C:\Users\william\Documents\ImportData\src\neo4j.ts:28:35)
    at Object.<anonymous> (C:\Users\william\Documents\ImportData\src\index.ts:41:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (C:\Users\william\Documents\ImportData\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\william\Documents\ImportData\node_modules\ts-node\src\index.ts:442:12)
(node:9492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9492) UnhandledPromiseRejectionWarning: Neo4jError: Failed to establish connection in 5000ms
:
    at captureStacktrace (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\result.js:200:15)
    at new Result (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\result.js:73:19)
    at Session._run (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\session.js:173:14)
    at Session.run (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\session.js:154:19)
    at Object.createCityRelationToBook (C:\Users\william\Documents\ImportData\src\neo4j.ts:28:35)
    at Object.<anonymous> (C:\Users\william\Documents\ImportData\src\index.ts:41:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (C:\Users\william\Documents\ImportData\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\william\Documents\ImportData\node_modules\ts-node\src\index.ts:442:12)
(node:9492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9492) UnhandledPromiseRejectionWarning: Neo4jError: Failed to establish connection in 5000ms
:
    at captureStacktrace (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\result.js:200:15)
    at new Result (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\result.js:73:19)
    at Session._run (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\session.js:173:14)
    at Session.run (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\session.js:154:19)
    at Object.createCityRelationToBook (C:\Users\william\Documents\ImportData\src\neo4j.ts:28:35)
    at Object.<anonymous> (C:\Users\william\Documents\ImportData\src\index.ts:41:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (C:\Users\william\Documents\ImportData\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\william\Documents\ImportData\node_modules\ts-node\src\index.ts:442:12)
(node:9492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:9492) UnhandledPromiseRejectionWarning: Neo4jError: Failed to establish connection in 5000ms
:
    at captureStacktrace (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\result.js:200:15)
    at new Result (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\result.js:73:19)
    at Session._run (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\session.js:173:14)
    at Session.run (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\session.js:154:19)
    at Object.createCityRelationToBook (C:\Users\william\Documents\ImportData\src\neo4j.ts:28:35)
    at Object.<anonymous> (C:\Users\william\Documents\ImportData\src\index.ts:41:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (C:\Users\william\Documents\ImportData\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\william\Documents\ImportData\node_modules\ts-node\src\index.ts:442:12)
(node:9492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:9492) UnhandledPromiseRejectionWarning: Neo4jError: Failed to establish connection in 5000ms
:
    at captureStacktrace (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\result.js:200:15)
    at new Result (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\result.js:73:19)
    at Session._run (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\session.js:173:14)
    at Session.run (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\session.js:154:19)
    at Object.createCityRelationToBook (C:\Users\william\Documents\ImportData\src\neo4j.ts:28:35)
    at Object.<anonymous> (C:\Users\william\Documents\ImportData\src\index.ts:41:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (C:\Users\william\Documents\ImportData\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\william\Documents\ImportData\node_modules\ts-node\src\index.ts:442:12)
(node:9492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:9492) UnhandledPromiseRejectionWarning: Neo4jError: Failed to establish connection in 5000ms
:
    at captureStacktrace (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\result.js:200:15)
    at new Result (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\result.js:73:19)
    at Session._run (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\session.js:173:14)
    at Session.run (C:\Users\william\Documents\ImportData\node_modules\neo4j-driver\lib\v1\session.js:154:19)
    at Object.createCityRelationToBook (C:\Users\william\Documents\ImportData\src\neo4j.ts:28:35)
    at Object.<anonymous> (C:\Users\william\Documents\ImportData\src\index.ts:41:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (C:\Users\william\Documents\ImportData\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\william\Documents\ImportData\node_modules\ts-node\src\index.ts:442:12)
(node:9492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by ali-ince** [comment] 2019-08-26 11:22
Hi @2joocy,

The driver contains an internal connection pool with a `maxConnectionPoolSize` (default is `100`) and when it's already reached to its maximum (i.e. all the connections in the pool are busy carrying out user work on session objects) - pending connection acquisition requests are waited for `connectionAcquisitionTimeout` (default value is `5000` => 5 seconds) before failing with a `connection acquisition timed out` error.

Apart from this, there is also another timeout value enforced for connection establishment which is also configurable via `connectionTimeout`  (default value is `5000` => 5 seconds) and waits for any new connection request to succeed in this period of time and fails otherwise (with the error you're experiencing).

I'm not sure about the actual data size you have, but it might be related to the server load and it's not being able to cope with incoming requests because of ongoing high load. Would that be possible?

And having looked at your project code, I think it would be possible to simplify and optimise it's running time by making use of batched updates using `UNWIND` clause of cypher (more info can be found [here](https://medium.com/neo4j/5-tips-tricks-for-fast-batched-updates-of-graph-structures-with-neo4j-and-cypher-73c7f693c8cc)).

Finally, please ensure that you're using the latest version of the driver, which, for the time being, is `1.7.5`.

Please let us know if the issue still holds and provide sample data and reproduction steps for us to investigate more.

Thanks.

**Comment by zhenlineo** [comment] 2019-11-04 09:26
Hi @2joocy ,

I am closing this issue as we've not hear back from you for a long time. Please be free to reopen the issue if it is still a problem for you.

**Closed as completed by zhenlineo** 2019-11-04 09:26 UTC
