### ISSUE TITLE
v1 driver cannot resolve internal modules

### ISSUE THREAD

**Issue by Ethan-Arrowood** [neo4j/neo4j-javascript-driver#396] opened 2018-07-16 00:10 UTC
Installed most recent stable version of neo4j-driver today and when I try to launch my app I get the following error message: `Module not found: Can't resolve 'dns' in '/app/node_modules/neo4j-driver/lib/v1/internal'` (due note I'm using create-react-app and running the command `npm run start`)

I'll look into this issue and see if its just a bad publish or something else. Other recommendations would be helpful though.

**Comment by Ethan-Arrowood** [comment] 2018-07-16 00:24
Ahh this is not meant to run in the browser (see for more details https://github.com/facebook/create-react-app/issues/3543)

**Comment by lutovich** [comment] 2018-07-16 09:24
Hi @Ethan-Arrowood,

It is possible to use this driver in both browser and NodeJS environments. Modules like `dns` or `tls` do exist only in Node but driver tries to detect their presence at runtime and fallback to browser alternatives. Here is an example of the `dns` feature detection: [link](https://github.com/neo4j/neo4j-javascript-driver/blob/1.6.2/src/v1/internal/connection-providers.js#L247-L252).

Maybe this error has something to do with how modules are resolved by infrastructure created by create-react-app. I'll reopen this issue to investigate. Please feel free to update this issue if you have more details or steps to reproduce to share.

**Comment by Lynne-Daniels** [comment] 2018-07-29 04:21
Newbie here -- I'm just going to share my experience since a google search on `Can't resolve 'dns' in '/app/node_modules/neo4j-driver/lib/v1/internal` brought me right here.  My copy-paste attempt to use the 'Hello World' example at https://neo4j.com/docs/developer-manual/current/drivers/get-started/ failed with the same error.  Here are the changes that made it all work:


 ```// const uri = 'bolt://localhost:7687'  // seems to work with or without the port
const uri = 'bolt://localhost';
const neo4jDriver = require('neo4j-driver');
const driver = neo4jDriver.v1.driver(uri, neo4jDriver.v1.auth.basic('someuser', 'somepass'));```

Also had to create a user/password and give the user roles in the dashboard application.

**Comment by p1zz4br0etch3n** [comment] 2018-08-07 15:55
I also faced the problem using create-react-app and neo4j-driver@1.6.2. For me using `require` didn't solve the problem. But I found a workaround:
include the static web build (neo4j-web.min.js) in your index.html. Follow the docs about [public folder](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#using-the-public-folder) to do so and [global variables](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#using-global-variables) to access it.
I hope that helps.

**Comment by jeroenVerdonschot** [comment] 2018-09-18 15:47
Hi Guys,

Other newbie here. I have the same problem when testing in StackBlitz. 
@P1zz4br0etch3n would you be so kind to explain a bit more. 

Thanks!

Sorry found it I should use:
var driver = neo4j.v1.driver("bolt://localhost", neo4j.v1.auth.basic("neo4j", "neo4j"));

**Comment by p1zz4br0etch3n** [comment] 2018-09-18 16:35
Using `window.neo4j.v1 ...` is even better cause then it is obvious that you're using a global variable intentionally and your eslint doesn't warn you.

**Comment by lutovich** [comment] 2018-09-20 15:13
Dear All,

Module resolution errors seem to be caused by runtime feature detection in the driver. It contains Node and browser environment specific components in one codebase which confuses bundlers. They can't determine that Node components are unused and obviously fail at compile time when trying to resolve required Node APIs.

Probably the best workaround right now is to include `neo4j-web.min.js` in `index.js` as suggested by @P1zz4br0etch3n [here](https://github.com/neo4j/neo4j-javascript-driver/issues/396#issuecomment-411107571).

Mentioned PR should fix the problem and make it possible to use driver with a simple `import` or `require`. It will hopefylly go in 1.7 branch and be released in 1.7.0-beta02 available via `npm install --save neo4j-driver@next` pre-release channel.

**Closed as completed** 2018-09-27 18:24 UTC

**Comment by lutovich** [comment] 2018-09-28 10:03
Hello,

Pre-release 1.7.0-beta02 version of the driver with the fix is now released. It can be installed using `npm install --save neo4j-driver@next`. Please give it a try and let us know if there are any problems with it and Webpack. Thanks!

**Comment by p1zz4br0etch3n** [comment] 2018-10-01 08:51
Yep, now it works!
Thank you very much!
