### ISSUE TITLE
MaxConnectionPoolSize is not respected under heavy load

### ISSUE THREAD

**Issue by aaronjwood** [neo4j/neo4j-javascript-driver#501] opened 2019-11-20 19:14 UTC
The default internal connection pool size for this driver seems to be set at 100. I'm seeing that this can be broken. Basic test to reproduce this behavior:
```
    test('Connection pool', async () => {
        const driver = Neo4J.driver('bolt://localhost:7687', Neo4J.auth.basic('neo4j', 'neo4j'), {
            disableLosslessIntegers: true,
        });

        const p: Promise<any>[] = [];
        for (let i = 0; i < 1500; i++) {
            p.push(new Promise(async (res, rej) => {
                const session = driver.session();
                await session.run('MATCH (n) RETURN n');
                session.close();
                res();
            }));
        }

        await Promise.all(p);
    }, 30000);
```

Watch netstat while you run this test and see that the number of connections goes into the thousands:
```
watch -n .5 'netstat -an | grep "7687" | grep ESTABLISHED | wc -l'
```

I've tested this against Neo4j 3.5.3 and 3.5.12 using driver versions 1.7.5 and 4.0.0-beta01.

**Comment by zhenlineo** [comment] 2019-11-21 12:34
https://github.com/neo4j/neo4j-javascript-driver/pull/500

**Comment by zhenlineo** [comment] 2019-11-25 10:15
Hi @aaronjwood ,
Thanks very much for reporting this to us. We are releasing a new 4.0.0-rc1 driver with the fix inside. The fix ensures the maximum active connection count is always less or equal to `MaxConnectionPoolSize`.

**Comment by aaronjwood** [comment] 2019-12-01 13:02
Thanks! Any chance this can be backported to 1.7.x? I don't want to upgrade to the beta driver release.

**Comment by zhenlineo** [comment] 2019-12-01 19:11
Hi @aaronjwood,
The change was also merged in 1.7. But I currently do not have a patch release date for next 1.7. I will let you know once I got more information.

**Comment by zhenlineo** [comment] 2019-12-09 13:54
Hi @aaronjwood ,

The 4.0.0 js driver is fully released. It supports all 3.3+ servers. The API is slightly changed, you can read more [here](https://www.npmjs.com/package/neo4j-driver#whats-new).

Could you verify if the problem is solved and close this issue if it is no longer the problem? Or let us know if you think there is more need to be done.
Cheers,
Zhen

**Comment by aaronjwood** [comment] 2019-12-12 02:00
We hadn't planned on upgrading to 4.0.0 soon as the API has changed a bit and requires some work on our end to swap it in. I'll let you know if 4.0.0 fixes the issue when we upgrade to it but for now we've layered our own session pool on top of the lib to work around the issue.

**Closed as completed** 2020-03-19 15:55 UTC
