### ISSUE TITLE
Queries will hang arbitrarily

### ISSUE THREAD

**Issue by taimur38** [neo4j/neo4j-javascript-driver#148] opened 2016-09-29 18:55 UTC
```
const getOneResult = transaction => {
    const session = driver.session();

    return session.run(transaction)
        .then(result => {

            session.close();
            return result;
        })
        .catch(err => { console.log(err); throw new Error('fail'); })
};
```

Occasionally, this will hang on session.run for a long period of time (~60 seconds?). After that, we get a ETIMEDOUT error. Hit that function again and it works fine, so it randomly seems to do this.

**Comment by oskarhane** [comment] 2016-11-23 08:32
Hi @taimur38 and thanks for the report. Also, sorry for the late reply.

Is this still an issue? If so, can you provide more code to reproduce this since I cannot reproduce your issue using the code above.

What version of neo4j and the driver are you using? What OS are your running this on?

**Comment by lutovich** [comment] 2016-12-20 14:21
Hi @taimur38. This issue has been idle for some time now. Do you still have this problem?

**Comment by booboothefool** [comment] 2016-12-24 14:45
I am also having this issue: 

```
    "neo4j": "^2.0.0-RC2",
    "neo4j-driver": "^1.0.5",
```

An example of some code that does this (it seems to work about 90% of the time...):
```
  async getUserPersona(id) {
    let result = {};
    const session = this.connector.bolt.session();
    try {
      const cypherGetUserPersona = `
        MATCH (User {user_id: { id }})-[:PERSONIFIES]->(persona:Persona)-[:SOURCE]->(source)
        RETURN persona, collect(source) as sources
      `;
      const queryResult = await session.run(cypherGetUserPersona, { id });
      const persona = queryResult.records[0]._fields[0].properties;
      const sources = queryResult.records[0]._fields[1].map(source => source.properties);
      result = Object.assign(persona, { sources });
    } catch (error) {
      console.error('(getUserPersona) =>\t'.red, error);
    }
    session.close();
    return result;
  }
```

All of old code that uses https://github.com/thingdom/node-neo4j/tree/v2#readme, seems to work 100% of the time though, so I believe there may be something I'm unaware of when using this bolt driver.

**Comment by booboothefool** [comment] 2016-12-27 02:44
@taimur38 @oskarhane @lutovich  I am also having this issue: 

```
    "neo4j-driver": "^1.0.5",
```

An example of some code that does this `getUserPersona` (it seems to work about 90% of the time...):
```
var bolt = require('neo4j-driver').v1;

export class Neo4jConnector {
  constructor({ ... } = {}) {
    this.bolt = bolt.driver('bolt://___', bolt.auth.basic('___', '___'));
  }
}
```

```
export class Personas {
  constructor({ connector }) {
    this.connector = connector;
  }

  async getUserPersona(id) {
    let result = {};
    const session = this.connector.bolt.session();  // this.connector.bolt is the driver
    try {
      const cypherGetUserPersona = `
        MATCH (User {user_id: { id }})-[:PERSONIFIES]->(persona:Persona)-[:SOURCE]->(source)
        RETURN persona, collect(source) as sources
      `;
      const queryResult = await session.run(cypherGetUserPersona, { id });
      const persona = queryResult.records[0]._fields[0].properties;
      const sources = queryResult.records[0]._fields[1].map(source => source.properties);
      result = Object.assign(persona, { sources });
    } catch (error) {
      console.error('(getUserPersona) =>\t'.red, error);
    }
    session.close();
    return result;
  }

...
}
```

**Comment by lutovich** [comment] 2016-12-27 09:23
Hi @booboothefool,

Provided code looks correct to me. The only change I'd make would be moving `session.close()` line to be right after the `await session.run(...)`. This way `session.close()` won't be called when there is an error.

Do you also mind enabling slow query logging in the database? How-to is here: http://neo4j.com/docs/operations-manual/current/monitoring/logging/query-logging/.
It is to be sure driver is actually hanging and not just waiting for the database to execute the query.

To be able to reproduce this problem we'd need to generate a dataset similar to yours. Could you please share following info about your db:
 1) number of `User` nodes
 2) number of `Persona` nodes
 3) number of `source` nodes
 4) estimated number of relationships `PERSONIFIES` for a `User` node
 5) estimated number of relationships `SOURCE` for a `Persona` node

Thanks in advance!

**Comment by booboothefool** [comment] 2016-12-27 18:53
@lutovich I don't think I can enable the query logging. I am using http://www.graphenedb.com/pricing, which I believe requires a Performance plan for $400/month to enable that slow query logging? I am still in early development. :P 

number of User nodes: 2
number of Persona nodes: 2
number of source nodes: 10
estimated number of relationships PERSONIFIES for a User node: 1
estimated number of relationships SOURCE for a Persona node: 1-5

If you want to give me contact info, I can just send you an export of my entire database...

**Comment by booboothefool** [comment] 2016-12-27 21:50
@lutovich 

number of User nodes: 2
number of Persona nodes: 2
number of source nodes: 10
estimated number of relationships PERSONIFIES for a User node: 1
estimated number of relationships SOURCE for a Persona node: 1-5

If you want to give me contact info, I can just send you an export of my entire development database with 3 queries that seem to hang. I'm also willing to just give you my GrapheneDB password so you can see all the nodes in the database / queries I tried to use if you want, as the issue is extremely concerning to me.

I'm actually running many queries at a time (GraphQL). If I run a single query by itself, it seems to work, but they seem to hang when I try to do as little as 2.

**I can confirm that the issue only occurs when I try to run multiple queries via GraphQL**. Is there anything to be aware of when running simultaneous queries with bolt driver?

If it would be better, I can try to produce a minimal Node.js, GraphQL server you can hit to see the issue.

EDIT: **@lutovich** I sent you an invitation to a private repo minimal reproduction of the issue with all the info.

**Comment by lutovich** [comment] 2016-12-28 10:11
Thanks for the repro @booboothefool! I'll try it now.

It should be perfectly fine and supported to run simultaneous queries.

**Comment by lutovich** [comment] 2016-12-28 11:21
@booboothefool unfortunately I can't reproduce this issue by running GraphQL queries manually from browser. We could probably try to export database from GrapheneDB and run a local test with those two queries. They can run asynchronously using smth like http://caolan.github.io/async/docs.html#eachLimit for random `(:User {user_id})`. This way we could possibly isolate this issue to driver+neo4j.

Used database version in 3.0.8. Could you maybe try same test with 3.1.0?

Update: also tried scripting this with
```javascript
setInterval(
  function(){ document.getElementsByClassName("execute-button")[0].click(); },
  1000
);
```
from 5 different tabs and queries did not get stuck after an hour.

**Comment by booboothefool** [comment] 2016-12-28 17:03
@lutovich This is what I'm seeing with the instructions in the repo 🤔 , and how it functions in the production app too. 😢  

![stuckqueries](https://cloud.githubusercontent.com/assets/13257645/21526911/96a73758-ccf5-11e6-9ce1-df0e125c11a1.gif)

**Comment by lutovich** [comment] 2016-12-28 17:10
@booboothefool it hangs fast for you! what about `console.log` output? does it also stall?
can you somehow get a stacktrace of node app? maybe using this https://qzaidi.github.io/2012/08/05/pstack-for-nodejs/

**Comment by booboothefool** [comment] 2016-12-28 18:38
@lutovich Yes, the `console.log` output also stalls.

![stuckqueries](https://cloud.githubusercontent.com/assets/13257645/21528672/3a9e5b0a-cd02-11e6-9c90-05fc31702bc3.gif)

Where do you want the stack trace? I haven't found that very helpful considering there are no errors. Tried setting up that jsstack but it doesn't work for me.

**Comment by lutovich** [comment] 2016-12-29 09:03
@booboothefool stacktrace could be useful even without errors to figure out what the app is doing. Which node version are you using?

At this point I can only suggest adding logs around `session.run`, `session.close` and `this.connector.bolt.session()` to see which operation blocks. Also you should not close the driver after every operation. So `this.connector.bolt.close()` should only be done once when application shuts down.

**Comment by booboothefool** [comment] 2016-12-29 17:28
@lutovich It is definitely blocking in `session.run`. I have tried node `v6.9.2` and `v7.3.0`. Same issue on both. Also `macOS Sierra Version 10.12.1`.

I removed the `this.connector.bolt.close()` like you said and added some `console.log` to `session.run()`.
```
  _createClass(Session, [{
    key: 'run',
    value: function run(statement) {
      console.log('start session.run', statement);
      var parameters = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];

      if (typeof statement === 'object' && statement.text) {
        parameters = statement.parameters || {};
        statement = statement.text;
      }
      var streamObserver = new _RunObserver();
      if (!this._hasTx) {
        this._conn.run(statement, parameters, streamObserver);
        this._conn.pullAll(streamObserver);
        this._conn.sync();
      } else {
        streamObserver.onError((0, _error.newError)("Statements cannot be run directly on a " + "session with an open transaction; either run from within the " + "transaction or use a different session."));
      }
      return new _result2['default'](streamObserver, statement, parameters, function () {
        console.log('return session.run', statement);
        return streamObserver.meta();
      });
    }
```

When it blocks, `console.log('return session.run', statement);` is never hit. Also, I see an error when it blocks now! 

```
(getUserPersona) auth0|585c53237547f42fe4f92d55
start session.run
        MATCH (User {user_id: { id }})-[:PERSONIFIES]->(persona:Persona)-[:SOURCE]->(source)
        RETURN persona, collect(source) as sources

(getUserGames) auth0|585c53237547f42fe4f92d55
start session.run
        MATCH (user: User {user_id: { id }})-[r:PLAYS]->(game:Game)
        MATCH (game)-[:RELEASED]->(platform:Platform)
        MATCH (publisher:GameCompany)-[:PUBLISHED]->(game)
        MATCH (developer:GameCompany)-[:DEVELOPED]->(game)
        RETURN game, collect(DISTINCT platform) as platforms, collect(DISTINCT publisher) as publishers, collect(DISTINCT developer) as developers, r
        ORDER by r.order ASC

return session.run
        MATCH (User {user_id: { id }})-[:PERSONIFIES]->(persona:Persona)-[:SOURCE]->(source)
        RETURN persona, collect(source) as sources

(getUserPersona)[RETURN] =>	 result

/Users/a/code/GraphQL-Neo4j-StuckQueries/node_modules/neo4j-driver/lib/v1/internal/connector.js:349
            this._currentObserver.onError(msg);
                                 ^
TypeError: Cannot read property 'onError' of undefined
    at Connection._handleMessage (/Users/a/code/GraphQL-Neo4j-StuckQueries/node_modules/neo4j-driver/lib/v1/internal/connector.js:349:34)
    at Dechunker.Connection._dechunker.onmessage (/Users/a/code/GraphQL-Neo4j-StuckQueries/node_modules/neo4j-driver/lib/v1/internal/connector.js:281:12)
    at Dechunker._onHeader (/Users/a/code/GraphQL-Neo4j-StuckQueries/node_modules/neo4j-driver/lib/v1/internal/chunking.js:231:14)
    at Dechunker.AWAITING_CHUNK (/Users/a/code/GraphQL-Neo4j-StuckQueries/node_modules/neo4j-driver/lib/v1/internal/chunking.js:185:21)
    at Dechunker.write (/Users/a/code/GraphQL-Neo4j-StuckQueries/node_modules/neo4j-driver/lib/v1/internal/chunking.js:242:28)
    at NodeChannel.self._ch.onmessage (/Users/a/code/GraphQL-Neo4j-StuckQueries/node_modules/neo4j-driver/lib/v1/internal/connector.js:254:27)
    at TLSSocket.<anonymous> (/Users/a/code/GraphQL-Neo4j-StuckQueries/node_modules/neo4j-driver/lib/v1/internal/ch-node.js:274:16)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```
^ `getUserGames` never returned, I get the error, and server crashes.

**Comment by booboothefool** [comment] 2016-12-29 23:07
@lutovich I also noticed the chance of success is much better without `driver.close()` after `session.close()`. If I do `driver.close()` after every `session.close()`, it hangs almost every other time the user tries fetch their profile. Also note that that in the repo minimal reproduction, I am just doing 2 queries: `userPersona` and `userGames`. In production, I am fetching the entire user profile, their favorites (and their favorites' profile), etc, so the chances of one of the queries getting stuck there is much higher. XD

When I first noticed the issue, I had:
1)
```
try {
  ...
  await session.run();
} catch(error) {
  ...
}
session.close();
return result;
```

I then tried:
2)
```
try {
  ...
  await session.run();
  session.close();
  driver.close();
} catch(error) {
  ...
}
return result;
```
^ You said this was bad, and I did notice that it is MUCH more likely to block when I do this.

After your suggestions:
3)
```
try {
  ...
  await session.run();
  session.close();
} catch(error) {
  ...
}
return result;
```
3) seems to work the best. The issue still occurs as I reported, but it is much less likely. With 2) I can get it to hang really quickly (as you saw in my .gifs), but 3) not so much. Not sure if this is just coincidence or what. This issue is sort of above my ahead, so I hope some of this info is helpful.

It doesn't ever get stuck for you at all? 🤔 😢

**Comment by lutovich** [comment] 2016-12-30 08:40
@booboothefool your example never get stuck on my machine. Can't explain this really :(
When driver is closed as in (2) it should not be possible to obtain sessions from it afterwards. So code should fail really quickly. We are probably missing some `isClosed` check. Will create a task to add it.

I can also see lots of OOM errors in the database log. Those might be causes by unclosed sessions. Each session gets a thread on the server so many unclosed sessions mean high memory usage. Can I export that test db from GrapheneDB and play with it locally? I'd like to be able to take thread and heap dumps for three versions of the code you've mentioned.

**Comment by lutovich** [comment] 2016-12-30 09:53
@booboothefool I did not pay enough attention to `server.js` file. Just noticed that new driver was created for each request (via `new Neo4jConnector()`). Sent a PR with couple fixes. Please try them out. Also restarted the database.

**Comment by booboothefool** [comment] 2016-12-30 17:12
@lutovich That was it!!!! Ahh, so silly. 

Not only does it completely fix the issue (I can't get it to block at all anymore), but now the queries are super fast. They used to take about 500ms-1500ms, but now are instant. When I spam the query in GraphiQL, the spinner doesn't even move because it's too fast, hahaha! It's faster than I can blink! 👍 

Amazing. Fixes my app and makes it way way way faster.

Thank you so much for your help. So key thing to take from this all was: **MAKE SURE TO USE ONE INSTANCE OF DRIVER FOR APP**. My app is structured a lot like: https://github.com/apollostack/GitHunt-API/blob/master/api/index.js#L60 (my production app uses a lot more data sources than just Neo4j), so that's where `new` awfully wrong for the case of this driver, hahaha. 

Wooooo! 🎉 🎈 👍  It's super fast! I used to think "Umm Bolt doesn't seem to make that much of a difference...", but now I see I was just doing it wrong. >.> It is clearly blazing fast.

**GraphQL + Neo4j (with Bolt 😄 ) = winning combo**

(You're welcome to export that repo database if you still want to. It's all fake data I was just playing with.)

**Comment by lutovich** [comment] 2016-12-30 17:35
@booboothefool glad it works better now :)

I do not think I need to export that database. Found one unhandled exceptional condition in server part of Bolt that could also cause similar hanging. Will keep this issue open until that one is fixed.

**Comment by lutovich** [comment] 2017-02-07 13:30
Mentioned PR is now merged. Closing this issue.

**Closed as completed by lutovich** 2017-02-07 13:30 UTC
