### ISSUE TITLE
"Database has encountered some problem, please perform necessary action (tx recovery/restart)"

### ISSUE THREAD

**Issue by Jabher** [neo4j/neo4j-javascript-driver#300] opened 2017-10-04 11:55 UTC
Hi!
I'm getting this error in production:
```
server_1 | 0|server | error in transaction { Neo4jError: Database has encountered some problem, please perform necessary action (tx recovery/restart)
server_1 | 0|server | at new Neo4jError (/usr/src/app/node_modules/neo4j-driver/lib/v1/error.js:76:132)
server_1 | 0|server | at newError (/usr/src/app/node_modules/neo4j-driver/lib/v1/error.js:66:10)
server_1 | 0|server | at Connection._handleMessage (/usr/src/app/node_modules/neo4j-driver/lib/v1/internal/connector.js:355:56)
server_1 | 0|server | at Dechunker.Connection._dechunker.onmessage (/usr/src/app/node_modules/neo4j-driver/lib/v1/internal/connector.js:286:12)
server_1 | 0|server | at Dechunker._onHeader (/usr/src/app/node_modules/neo4j-driver/lib/v1/internal/chunking.js:246:14)
server_1 | 0|server | at Dechunker.AWAITING_CHUNK (/usr/src/app/node_modules/neo4j-driver/lib/v1/internal/chunking.js:199:21)
server_1 | 0|server | at Dechunker.write (/usr/src/app/node_modules/neo4j-driver/lib/v1/internal/chunking.js:257:28)
server_1 | 0|server | at NodeChannel.self._ch.onmessage (/usr/src/app/node_modules/neo4j-driver/lib/v1/internal/connector.js:259:27)
server_1 | 0|server | at TLSSocket.<anonymous> (/usr/src/app/node_modules/neo4j-driver/lib/v1/internal/ch-node.js:308:16)
server_1 | 0|server | at emitOne (events.js:120:20)
server_1 | 0|server | at TLSSocket.emit (events.js:210:7)
server_1 | 0|server | at addChunk (_stream_readable.js:266:12)
server_1 | 0|server | at readableAddChunk (_stream_readable.js:253:11)
server_1 | 0|server | at TLSSocket.Readable.push (_stream_readable.js:211:10)
server_1 | 0|server | at TLSWrap.onread [as _originalOnread] (net.js:585:20)
server_1 | 0|server | at TLSWrap.onread (/usr/src/app/node_modules/async-listener/glue.js:188:31)
server_1 | 0|server | code: 'Neo.DatabaseError.Transaction.TransactionStartFailed'
```

And after that database connection is crashed and I have to restart an instance.
But there is no such method as `tx.recovery()` or `tx.restart()`.

What should I do?

**Comment by lutovich** [comment] 2017-10-04 12:11
Hi @Jabher,

This error comes from server and can't really be handled on the client side in driver.
Error message is confusing and does not actually mean `tx.recovery()` or `tx.restart()` should be called. We will fix the message.

Errors like this usually indicate that database has encountered a serious error and was not able to commit a transaction. Such errors are OOMs, insufficient disk space, etc. Could you please attach `debug.log` from your database as github gist? It will hopefully show us what happened in the database.

**Comment by MishaDemianenko** [comment] 2017-10-04 15:34
Critical message updated as part of https://github.com/neo4j/neo4j/pull/10211

**Comment by Jabher** [comment] 2017-10-04 15:40
In brief - I ran out of disk space yesterday, got really weird message "Unknown entry type 95 for version 0. At position LogPosition{logVersion=0, byteOffset=7077913} and entry version V2_0" (full log is here https://gist.github.com/Jabher/2fb5ab7261f310d5c15e76f5ab8e709f).
I've tried to recover database, only thing that helped was removing the transaction file (data/databases/graph.db/neostore.transaction.db.0) and (somewhy) moving from 3.2.2 to 3.2.5 version of neo4j docker build, after that the DB started working as expected, so I thought it was something related to transactions.

But today my server gone crazy and is failing every hour or half an hour with that error, I'm going to dump and undump database (like fresh installation) this night.

I'm not sure about how exactly this is happening but it feels like it acts in that way when I'm trying to perform 2 concurrent transactions with creation of record which is having same property which is asserted to be unique.

I'm using auth0, so I have middleware with transaction that acts "create user with this auth0id if not exists" on every request, and auth0id property is asserted as unique.

But I totally have no idea how to fix it.

**Comment by lutovich** [comment] 2017-10-04 16:13
I understand the problem. It looks like write ahead log got corrupted because database ran out of disk space. Unfortunately, only recent 3.4 snapshot builds are able to handle this kind of problem.

Could you please run consistency check on your store? It is part of `neo4j-admin` command and here is manual for it: https://neo4j.com/docs/operations-manual/current/tools/consistency-checker/. It would be valuable for us to see it's output.

You can also use store-copy tool from here: https://github.com/jexp/store-utils to dump and undump the database. Please do a backup first (either by copying `graph.db` directory or using the backup tool).

Hope this helps!

I'll close this issue now because it is not related to JS driver. However please post back about your progress!

**Closed as completed by lutovich** 2017-10-04 16:13 UTC

**Comment by Jabher** [comment] 2017-10-04 16:29
I've tried it. How it's even working? O_o
https://gist.github.com/Jabher/8ca4340a6787638318b327cb2e079c69

**Comment by Jabher** [comment] 2017-10-04 16:52
That did not work :( I will probably will make some kind of JSON dump back and forth

**Comment by lutovich** [comment] 2017-10-04 16:53
Did you get an error from the tool? Did you use 3.2 branch from here: https://github.com/jexp/store-utils/tree/32?

**Comment by Jabher** [comment] 2017-10-04 18:11
yes, same errors for 31 and 32

https://gist.github.com/Jabher/e57655985646df625eb679f097b6fde1

**Comment by lutovich** [comment] 2017-10-04 19:04
@Jabher you can try one more think to make store-copy tool work. Try moving `neostore.counts.db.a` and `neostore.counts.db.b` files away from `graph.db` folder and restarting the db. They represent and auxiliary structure - counts store. Database can recover this information during startup and regenerate them. After this store-copy tool might be able to work.

**Comment by Jabher** [comment] 2017-10-05 07:31
That worked! Thanks a lot, I really appreciate your help. I think I owe you some good PR :) 
Wish this "recovery guide" would be somewhere in public

**Comment by lutovich** [comment] 2017-10-05 08:09
Great! The problem is that we can't create a generic guide for such situations. Generally removal of database files is extremely unsafe, even if they are transaction logs, counts store, etc. It is always better to raise an issue so we can take a look, suggest a solution and know what kind of problems users have.

Have a good day!

**Comment by lutovich** [comment] 2017-10-05 08:51
I'd also like to mention that because of the out of disk space issue and transaction log removal some data might be lost. It should not be a lot but I'd recommend checking logical integrity of data, if possible.
