### ISSUE TITLE
'beginning implicit transaction' cannot be done when a session is in the 'IN_TRANSACTION' state

### ISSUE THREAD

**Issue by cipacda** [neo4j/neo4j-javascript-driver#166] opened 2016-11-25 13:38 UTC
- Neo4j version: 3.0.6
- Operating system: Windows 8 and 10
- API/Driver: Neo4j Javascript driver - neo4j-driver@1.1.0-M02

##Steps to reproduce##
Run two sessions updating the same node at the same time. 

What I am doing is having an asynchronous neo4j endpoint that returns before it finishes adding a relation to a specific node and then immediately I have another synchronous endpoint called that adds another relation to that node, both actions being executed inside a transaction.

##Expected behavior##
To get a deadlock error on the second query and then when I am retrying the transaction for it to succeed.

##Actual behavior##
I am getting a deadlock on the 4th query inside my transaction and then when I am retrying the transaction (by creating a new one with the same queries) I get the following: {"code":"Neo.ClientError.Request.Invalid","message":"'beginning implicit transaction' cannot be done when a session is in the 'IN_TRANSACTION' state."}

##Additional comments##
This is my code with sensitive data taken out: 
```
function transactionFunction(txn: any)  {

   return txn.run(query1)
     .then(_ => { return txn.run(query2); })
     .then(_ => { return txn.run(query3); })
     .then(_ => { return txn.run(query4); })
}

export function runInsideTransaction(session, runFunction: (txn) => Promise<any>): Promise<any> {
    function retry(times: number): Promise<any> {
        car result;
        var txn = createTransaction(session);
        return new Promise((resolve, reject) => {
            runFunction(txn)
                .then(response => {
                    result = response;
                    return commitTransaction(txn);
                })
                .then(() => {
                    resolve(result);
                })
                .catch((error) => {
                    // We should retry deadlocks
                    var code = (error.fields && error.fields[0]) ? error.fields[0].code : null;
                    if (times > 0 && code && code.indexOf('Neo.TransientError.Transaction.DeadlockDetected') > -1) {
                            retry(times - 1)
                                .then(response => {
                                    resolve(response);
                                })
                                .catch(e => {
                                    reject(e);
                                });
                        });
                    } else {
                        reject(error);
                    }
                });
        });
    }
    
    return retry(5);
}

runInsideTransaction(session, transactionFunction);
```

I am creating a session that outside that is only used here and I have logged everything and the _hasTx property of the session is false when we try the transaction the second time.

I have looked at the source code of the javascript driver and did not find this error which makes me believe this is actually a Neo4J bug?

I have reported this on the neo4j repo as well.

Anyone has any thoughts?

**Comment by lutovich** [comment] 2016-12-16 16:23
Hi @cipacda,

Thanks for reporting this issue and sorry for the delayed response.
Error indeed comes from Neo4j but it is most likely caused by the way driver interacts with the database. It looks awfully similar to the issue fixed in this PR https://github.com/neo4j/neo4j-javascript-driver/pull/173. Unfortunately this fix has not yet been released.

Would it be ok for you to attempt reproduce this problem when the fix is released? I'll update this ticket when it is.

**Comment by cipacda** [comment] 2016-12-19 08:18
@lutovich, do you know when that will be released?

I do have a replication case and can test it once it is released but this is also blocking us and we need to have a live release early January.

**Comment by lutovich** [comment] 2016-12-19 08:54
@cipacda Stable 1.1 driver version should be released around mid January but a milestone with the fix should be out this week. However I would not recommend using pre-release versions in production. Could you maybe try latest 1.0.5 release from npm? If error persists we could try https://github.com/neo4j/neo4j-javascript-driver/pull/173 fix on 1.0 branch and do a release there.

**Comment by technige** [comment] 2017-01-03 10:06
Full 1.1 driver release is scheduled for 19 Jan.

**Comment by cipacda** [comment] 2017-01-03 15:48
Sorry, been away and did not have a chance to test this. From the commits on the 1.0.5 tag it doesn't look like #173 is included in there.  Would it be possible to have 1.1-rc1 or similar, to test whether the above is fixed before 19th of January?

**Comment by lutovich** [comment] 2017-01-03 16:11
@cipacda this fix has been released in 1.1.0-M04, see tag here https://github.com/neo4j/neo4j-javascript-driver/commit/c94c2cdc36360e65c76837609fe10ec82ef67cf5. Please try it out and let us know if the problem is resolved.

**Comment by cipacda** [comment] 2017-01-05 08:40
I have tested this on 1.1.0-M04 and this looks to be fixed, thanks!

**Comment by lutovich** [comment] 2017-01-05 09:13
@cipacda great to hear this! Closing this issue.

**Closed as completed by lutovich** 2017-01-05 09:13 UTC
