### ISSUE TITLE
JavaScript issue with Cypher generating floating instead of integer when using LIMIT in query

### ISSUE THREAD

**Issue by musachi** [neo4j/neo4j-javascript-driver#1042] opened 2022-12-25 21:04 UTC
This works fine:

`session.run('MATCH (user: User) RETURN user ORDER BY user.name OFFSET $offset LIMIT toInteger($limit)', {
    offset: 0,
    limit: neo4j.int(30)
})`

But when I use this other query:

`session.run('MATCH (user:User)-[relation]->(profile)  
MATCH (profile)-[rel:HAS_ART {main: true}]->(art:Art)  
   OPTIONAL MATCH (profile)-[rel_arts:HAS_ART]->(arts:Art)  
   WHERE rel_arts.main IS NULL  
   RETURN user, art.name AS art, COLLECT(arts.name) AS arts ORDER BY user.name SKIP $offset LIMIT toInteger($limit)', {  
       offset: 0,
       limit: neo4j.int(30)
})`

I  got this error:
Neo4jError: LIMIT: Invalid input. '30.0' is not a valid value. Must be a non-negative integer.

I don't know why, I just changed the query.

node: v18.12.1

Neo4j: neo4j-community-5.1.0

neo4j-driver": "^5.3.0"

macOS: 12.6.2

**Comment by bigmontz** [comment] 2023-01-05 10:38
Hey @musachi, 

the problem can be fixed by set the `offset` also as an integer or by `neo4j.int(0)` or by using bigint, `0n`. I will check why the error report is not correct.

Btw, you don't need the `toInteger` in the query.

**Comment by bigmontz** [comment] 2023-01-12 08:59
The validation message point the error on the 30.0 because the error happens after sum the offset and the limit (0.0 + 30 = 30.0). This information can be found running `EXPLAIN` on the query. 

I re-direct the demand to the team responsible for the cypher language. 

I will close this issue since the issue is not related to the javascript driver.

Thanks for reporting. I will close the PR, but you can feel free to add additional comments.

**Closed as completed by bigmontz** 2023-01-12 08:59 UTC
Labels: bug
