### ISSUE TITLE
JS neo4j-driver - version 1.7.3 does not execute queries with parameters against database with Neo4j version 3.5.2

### ISSUE THREAD

**Issue by cameliaben** [neo4j/neo4j-javascript-driver#445] opened 2019-03-07 16:02 UTC
Hello,

I have noticed that executing queries from a NodeJS application, using **neo4j-driver version 1.7.3**, is not working against **Neo4j database with version 3.5.2**,  for **parameterized queries**, like below:
` 
// CASE 1 - promise based approach :
session.run( query, param ).then( ( result ) => {
        console.log( result );
    } )
    .catch( err => console.log( err ) );

//-----------------------------------------------------------------------
//CASE 2 - streaming-based approach: 
    session.run( query, param )
    .subscribe ( {
        onNext ( record ) {
            console.log( record );
        },
        onCompleted ( result ) {
            console.log( result );
            session.close();
        },
        onError ( error ) {
            console.log( error );
            session.close();
        },
    } );`

Both approaches log only query statistics, no results retrieved, although the same query executed on GrapheneDB client produces results. 
 Queries that do not have parameters execute as expected on Neo4j DB , version 3.5.2.

Both above approaches execute as expected against Neo4j database version 3.3.9, hosted on Graphene DB.

**Is there any known compatibility issue between neo4j-driver, v1.73 and Neo4j Database, 3.5.2 ?**

**Comment by zhenlineo** [comment] 2019-03-08 08:59
Hi @cameliaben 
In our tests, we have no problem to run parameterised queries against the database. 1.7 drivers are compatible with database 3.5 to 3.2 series.

For example the queries used in our [examples](https://neo4j.com/docs/driver-manual/current/sessions-transactions/) are all verified.

**Comment by technige** [comment] 2019-04-25 09:28
Closing issue as unable to reproduce. Please reopen if more information emerges.

**Closed as completed by technige** 2019-04-25 09:28 UTC
