### ISSUE TITLE
how to specific the port for driver?

### ISSUE THREAD

**Issue by linonetwo** [neo4j/neo4j-javascript-driver#67] opened 2016-05-05 07:16 UTC
When using docker, neo4j may have port 10452 or so, not conventional 7474, 
and the database may use ip 192.168.99.100. 

So should I use this?:

``` javascript
const driver = neo4j.driver('bolt://' + hostname + ':' + port , neo4j.auth.basic(userName, passWord));
```

What I tested out is that bolt://192.168.99.100 is OK when docker is running at 192.168.99.100, but 192.168.99.100:7474 is not working. So there is no way to a specific port?

And, should I always end the session using session.close() after something ?
I doubt I can use one session for the entire run time, and don't even close manually. Will it be automatically closed?

Thanks!

**Comment by pontusmelke** [comment] 2016-05-06 06:58
Hi,
It should work to specify the port via `host:port`. However `7474` is the port used by the http endpoint, the driver uses bolt which by default uses port `7687`. Could that be the cause of your problem?

Sessions should always be closed, the driver maintains a pool of sessions and by calling close you are effectively handing the session back to the pool so that the driver can reuse it. What is stopping you from closing the session? 

Thanks for reporting!

**Comment by linonetwo** [comment] 2016-05-06 18:29
Port 7687 works.
It's the first time I meet it ... so I mengbi for a while hhh

For the session, I previously thought I would send multiple requests to the REST endpoint of API server, so I should keep session for a faster visit. 
But actually, if I want to keep the session, I should use socket.io .That's my being too naive.

**Closed as completed** 2016-05-08 11:31 UTC
