### ISSUE TITLE
Concurrent db call gets terminated, even if the connectionPoolSize: 50 is set.

### ISSUE THREAD

**Issue by jaags** [neo4j/neo4j-javascript-driver#168] opened 2016-11-29 19:12 UTC
Just 2 call simultaneously gives this error.

Structure { 
  signature: 127,
  fields: 
   [ { code: 'Neo.TransientError.Transaction.Terminated',
       message: 'The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. Explicitly terminated by the user. ' } ] }

**Comment by lutovich** [comment] 2016-12-20 13:53
Hi @jaags,

Could you please share more details about this issue?
Which JS driver version and which neo4j version are you using?
What queries do you execute? Maybe you have a reliable script to reproduce?

Thanks in advance!

**Comment by technige** [comment] 2017-01-03 10:01
Closing, please re-open if more information is available.

**Closed as completed by technige** 2017-01-03 10:01 UTC

**Comment by acis** [comment] 2017-05-25 10:34
I have the same problem with 
Neo4J 3.0.8
neo4j-driver 1.1.1

` function (data) {
      db.getSomeData(data);
      db.getSomeMoreData(data);
  })`

Where the two db calls are queries that work on the same data set. 
I assume this is because of the way Neo4J uses read locks, but as these are both read queries, the lock should be shared, in theory.

**Comment by lutovich** [comment] 2017-05-30 08:30
Hi @acis,

Transactions can not be terminated because of read locks. Especially with a message like this.
Could you please share more details about your environment & provide a script to reproduce the problem?

**Comment by anti-peng** [comment] 2018-03-20 07:17
Since it has been quite a long time and this issue has been closed, I'm not sure if it's OK to append my same issue here.
I'm running neo4j-enterprise-3.2.3 on ubuntu 14.04, execute cypher through HTTP API. 
All the other queries are OK and passed performance test but this cypher down below
```
MATCH p=(a:Company)-[:LEGAL|INVEST|EMPLOY*..3]-(b:Company)
WHERE a.keyNo = {id1} AND b.keyNo = {id2}
RETURN relationships(p)[..100] AS rels
union
MATCH p=(a:Company)-[:LEGAL|INVEST|EMPLOY*..3]-(b:Company)
WHERE a.keyNo = {id1} AND b.keyNo = {id3}
RETURN relationships(p)[..100] AS rels
union
MATCH p=(a:Company)-[:LEGAL|INVEST|EMPLOY*..3]-(b:Person)
WHERE a.keyNo = {id1} AND b.keyNo = {id4}
RETURN relationships(p)[..100] AS rels
union
MATCH p=(a:Company)-[:LEGAL|INVEST|EMPLOY*..3]-(b:Company)
WHERE a.keyNo = {id1} AND b.keyNo = {id5}
RETURN relationships(p)[..100] AS rels
union
MATCH p=(a:Company)-[:LEGAL|INVEST|EMPLOY*..3]-(b:Company)
WHERE a.keyNo = {id2} AND b.keyNo = {id3}
RETURN relationships(p)[..100] AS rels
union
MATCH p=(a:Company)-[:LEGAL|INVEST|EMPLOY*..3]-(b:Person)
WHERE a.keyNo = {id2} AND b.keyNo = {id4}
RETURN relationships(p)[..100] AS rels
union
MATCH p=(a:Company)-[:LEGAL|INVEST|EMPLOY*..3]-(b:Company)
WHERE a.keyNo = {id2} AND b.keyNo = {id5}
RETURN relationships(p)[..100] AS rels
union
MATCH p=(a:Company)-[:LEGAL|INVEST|EMPLOY*..3]-(b:Person)
WHERE a.keyNo = {id3} AND b.keyNo = {id4}
RETURN relationships(p)[..100] AS rels
union
MATCH p=(a:Company)-[:LEGAL|INVEST|EMPLOY*..3]-(b:Company)
WHERE a.keyNo = {id3} AND b.keyNo = {id5}
RETURN relationships(p)[..100] AS rels
union
MATCH p=(a:Person)-[:LEGAL|INVEST|EMPLOY*..3]-(b:Company)
WHERE a.keyNo = {id4} AND b.keyNo = {id5}
RETURN relationships(p)[..100] AS rels
```
It's about one out of every four requests that I get this error
```
{
  "code": "Neo.DatabaseError.Statement.ExecutionFailed",
  "message": "The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. Explicitly terminated by the user. ",
  "stackTrace": "org.neo4j.graphdb.TransactionTerminatedException: The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. Explicitly terminated by the user. \n\tat org.neo4j.kernel.impl.api.KernelStatement.assertOpen(KernelStatement.java:193)\n\tat org.neo4j.kernel.impl.api.store.StorePropertyCursor.value(StorePropertyCursor.java:106)\n\tat org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodeGetProperty(StateHandlingStatementOperations.java:294)\n\tat org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.nodeGetProperty(ConstraintEnforcingEntityOperations.java:503)\n\tat org.neo4j.kernel.impl.api.OperationsFacade.nodeGetProperty(OperationsFacade.java:302)\n\tat org.neo4j.cypher.internal.spi.v3_2.TransactionBoundQueryContext$NodeOperations.getProperty(TransactionBoundQueryContext.scala:313)\n\tat org.neo4j.cypher.internal.compatibility.v3_2.ExceptionTranslatingQueryContext$ExceptionTranslatingOperations$$anonfun$getProperty$1.apply(ExceptionTranslatingQueryContext.scala:253)\n\tat org.neo4j.cypher.internal.spi.v3_2.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:32)\n\tat org.neo4j.cypher.internal.compatibility.v3_2.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:34)\n\tat org.neo4j.cypher.internal.compatibility.v3_2.ExceptionTranslatingQueryContext$ExceptionTranslatingOperations.getProperty(ExceptionTranslatingQueryContext.scala:253)\n\tat org.neo4j.cypher.internal.compiler.v3_2.commands.expressions.Property.apply(Property.scala:37)\n\tat org.neo4j.cypher.internal.compiler.v3_2.commands.predicates.Equals.isMatch(ComparablePredicate.scala:61)\n\tat org.neo4j.cypher.internal.compiler.v3_2.commands.predicates.CompositeBooleanPredicate$$anonfun$1$$anonfun$2.apply(Predicate.scala:76)\n\tat org.neo4j.cypher.internal.compiler.v3_2.commands.predicates.CompositeBooleanPredicate$$anonfun$1$$anonfun$2.apply(Predicate.scala:76)\n\tat scala.util.Try$.apply(Try.scala:192)\n\tat org.neo4j.cypher.internal.compiler.v3_2.commands.predicates.CompositeBooleanPredicate$$anonfun$1.apply(Predicate.scala:76)\n\tat org.neo4j.cypher.internal.compiler.v3_2.commands.predicates.CompositeBooleanPredicate$$anonfun$1.apply(Predicate.scala:71)\n\tat org.neo4j.cypher.internal.frontend.v3_2.helpers.NonEmptyList$class.foldLeftLoop(NonEmptyList.scala:255)\n\tat org.neo4j.cypher.internal.frontend.v3_2.helpers.NonEmptyList$class.foldLeft(NonEmptyList.scala:183)\n\tat org.neo4j.cypher.internal.frontend.v3_2.helpers.Fby.foldLeft(NonEmptyList.scala:301)\n\tat org.neo4j.cypher.internal.compiler.v3_2.commands.predicates.CompositeBooleanPredicate.isMatch(Predicate.scala:71)\n\tat org.neo4j.cypher.internal.compiler.v3_2.commands.predicates.Predicate.isTrue(Predicate.scala:35)\n\tat org.neo4j.cypher.internal.compiler.v3_2.pipes.FilterPipe$$anonfun$internalCreateResults$1.apply(FilterPipe.scala:33)\n\tat org.neo4j.cypher.internal.compiler.v3_2.pipes.FilterPipe$$anonfun$internalCreateResults$1.apply(FilterPipe.scala:33)\n\tat scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:463)\n\tat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)\n\tat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)\n\tat org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator$$anonfun$hasNext$1.apply$mcZ$sp(ResultIterator.scala:60)\n\tat org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator$$anonfun$hasNext$1.apply(ResultIterator.scala:58)\n\tat org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator$$anonfun$hasNext$1.apply(ResultIterator.scala:58)\n\tat org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator$$anonfun$failIfThrows$1.apply(ResultIterator.scala:94)\n\tat org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator.decoratedCypherException(ResultIterator.scala:103)\n\tat org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator.failIfThrows(ResultIterator.scala:92)\n\tat org.neo4j.cypher.internal.compiler.v3_2.ClosingIterator.hasNext(ResultIterator.scala:57)\n\tat org.neo4j.cypher.internal.compiler.v3_2.PipeExecutionResult.hasNext(PipeExecutionResult.scala:77)\n\tat org.neo4j.cypher.internal.compiler.v3_2.helpers.RuntimeJavaValueConverter$feedIteratorToVisitable.accept(RuntimeJavaValueConverter.scala:53)\n\tat org.neo4j.cypher.internal.compiler.v3_2.PipeExecutionResult.accept(PipeExecutionResult.scala:109)\n\tat org.neo4j.cypher.internal.compatibility.v3_2.ExecutionResultWrapper.accept(ExecutionResultWrapper.scala:159)\n\tat org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$1.apply$mcV$sp(ClosingExecutionResult.scala:169)\n\tat org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$1.apply(ClosingExecutionResult.scala:168)\n\tat org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$1.apply(ClosingExecutionResult.scala:168)\n\tat org.neo4j.cypher.internal.compatibility.v3_2.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)\n\tat org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:168)\n\tat org.neo4j.cypher.internal.javacompat.ExecutionResult.accept(ExecutionResult.java:318)\n\tat org.neo4j.server.rest.transactional.ExecutionResultSerializer.writeRows(ExecutionResultSerializer.java:444)\n\tat org.neo4j.server.rest.transactional.ExecutionResultSerializer.statementResult(ExecutionResultSerializer.java:112)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.executeStatements(TransactionHandle.java:324)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:157)\n\tat org.neo4j.server.rest.web.TransactionalService.lambda$executeStatementsAndCommit$1(TransactionalService.java:217)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)\n\tat com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)\n\tat com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)\n\tat org.neo4j.server.rest.dbms.AuthorizationEnabledFilter.doFilter(AuthorizationEnabledFilter.java:122)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)\n\tat java.lang.Thread.run(Thread.java:748)\n"
}
```

**Comment by mogadanez** [comment] 2019-07-04 10:55
I have same issue, but  it happens sometimes without stable reproduce.
All my queries is read. 

all endpoints  is wrapped in :
```
async (req, res) => {
                let session = driver.session()
                try {
                    let result = await SomService.getDetails(session, ..... )
                    res.json( result )
                }
                finally {
                    session.close()
                }

```
