### ISSUE TITLE
Weird return value when returning more then 82 nodes

### ISSUE THREAD

**Issue by royipressburger** [neo4j/neo4j-javascript-driver#71] opened 2016-05-10 19:01 UTC
Hi all

I have 88 node labeled with `Interest` When trying to query to get all of them Im running the next query:

```
MATCH (interest:Interest)
return properties(interest) as interest
```

It looks like that when im getting the values one of the values looks like that: 
![selection_004](https://cloud.githubusercontent.com/assets/9999184/15158876/77176630-16fa-11e6-8cf0-d589fffa7d5e.png)

when running the same query via the browser all seems to work as expected.

Now if i take the query and run it with `LIMIT 81` all still works but when the limit is more then 81 i get that weird node.. 

any ideas?

**Comment by pontusmelke** [comment] 2016-05-11 07:52
Hi, this is most likely a duplicate of https://github.com/neo4j/neo4j-javascript-driver/issues/64
The issue has been fix and an update will roll out soon. Please follow the updates in the other issue, if your issue still remains after the fix has rolled out don't hesitate to reopen this issue.

**Closed as completed by pontusmelke** 2016-05-11 07:52 UTC
